# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homebrew < Formula
  desc "CLI for the Skpr Hosting Platform"
  homepage "https://www.skpr.io"
  version "0.32.0"

  depends_on "docker" => :optional
  depends_on "rsync" => :optional

  on_macos do
    on_intel do
      url "https://github.com/skpr/cli/releases/download/v0.32.0/skpr_0.32.0_macOS_amd64.tar.gz"
      sha256 "35f8bea83845748d29a8980926cd9bf85296acac8af50a3a92c0256ea0c94149"

      def install
        bin.install "skpr"
        bin.install "skpr-rsh"

        man1.install "share/man/man1/skpr.1"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
        (bash_completion/"skpr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
        (zsh_completion/"_skpr").write output
      end
    end
    on_arm do
      url "https://github.com/skpr/cli/releases/download/v0.32.0/skpr_0.32.0_macOS_arm64.tar.gz"
      sha256 "f579f7de1844b8e03fe2ccb2c7f89c832588c96f9a9ccd4210eee0793507094c"

      def install
        bin.install "skpr"
        bin.install "skpr-rsh"

        man1.install "share/man/man1/skpr.1"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
        (bash_completion/"skpr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
        (zsh_completion/"_skpr").write output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skpr/cli/releases/download/v0.32.0/skpr_0.32.0_linux_amd64.tar.gz"
        sha256 "75d78e7f167b0c184ab76d6bc0b2c1035b8f596937b2d641ca8819bfffbc4189"

        def install
          bin.install "skpr"
          bin.install "skpr-rsh"

          man1.install "share/man/man1/skpr.1"

          # Install bash completion
          output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
          (bash_completion/"skpr").write output

          # Install zsh completion
          output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
          (zsh_completion/"_skpr").write output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skpr/cli/releases/download/v0.32.0/skpr_0.32.0_linux_arm64.tar.gz"
        sha256 "e6d2cace29f7a7def52455d070d4e803dd1efd69355276e96866c778f828b667"

        def install
          bin.install "skpr"
          bin.install "skpr-rsh"

          man1.install "share/man/man1/skpr.1"

          # Install bash completion
          output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
          (bash_completion/"skpr").write output

          # Install zsh completion
          output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
          (zsh_completion/"_skpr").write output
        end
      end
    end
  end
end
