# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skpr < Formula
  desc "CLI for the Skpr Hosting Platform"
  homepage "https://www.skpr.io"
  version "0.18.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/skpr/cli/releases/download/v0.18.1/skpr_0.18.1_macOS_arm64.tar.gz"
      sha256 "85a3f57da3eabbf2340423c6b6cc83c249b1d728e55a3a1afa1fbc99cfd0e1df"

      def install
        bin.install "skpr"
        bin.install "skpr-rsh"

        man1.install "share/man/man1/skpr.1"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
        (bash_completion/"skpr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
        (zsh_completion/"_skpr").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/skpr/cli/releases/download/v0.18.1/skpr_0.18.1_macOS_amd64.tar.gz"
      sha256 "6485349daf1ab5f22377cfc8556774ee5995a99fc4687fd8c9223d66ba6c0c83"

      def install
        bin.install "skpr"
        bin.install "skpr-rsh"

        man1.install "share/man/man1/skpr.1"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
        (bash_completion/"skpr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
        (zsh_completion/"_skpr").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skpr/cli/releases/download/v0.18.1/skpr_0.18.1_linux_arm64.tar.gz"
      sha256 "9c0b6a699e95f04e3290dedc0bb16babb8a1b7000bd531e62129ad0a23a4812d"

      def install
        bin.install "skpr"
        bin.install "skpr-rsh"

        man1.install "share/man/man1/skpr.1"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
        (bash_completion/"skpr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
        (zsh_completion/"_skpr").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/skpr/cli/releases/download/v0.18.1/skpr_0.18.1_linux_amd64.tar.gz"
      sha256 "aac9861737a490c4f883bceca4b82f23fa36ef74bb6cb1077063517efcaf034a"

      def install
        bin.install "skpr"
        bin.install "skpr-rsh"

        man1.install "share/man/man1/skpr.1"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
        (bash_completion/"skpr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
        (zsh_completion/"_skpr").write output
      end
    end
  end

  depends_on "rsync" => :optional
  depends_on "docker" => :optional
end
