# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skpr < Formula
  desc "CLI for the Skpr Hosting Platform"
  homepage "https://www.skpr.io"
  version "0.29.2"

  depends_on "docker" => :optional
  depends_on "rsync" => :optional

  on_macos do
    on_intel do
      url "https://github.com/skpr/cli/releases/download/v0.29.2/skpr_0.29.2_macOS_amd64.tar.gz"
      sha256 "836de0a51a72ce1be0a3fb22dfee3d78e3b1429884df30df6b14928c018264d9"

      def install
        bin.install "skpr"
        bin.install "skpr-rsh"

        man1.install "share/man/man1/skpr.1"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
        (bash_completion/"skpr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
        (zsh_completion/"_skpr").write output
      end
    end
    on_arm do
      url "https://github.com/skpr/cli/releases/download/v0.29.2/skpr_0.29.2_macOS_arm64.tar.gz"
      sha256 "0d24100ab847851d873f2f2dc14f852a70fb0f32b692a3a7ebf8083c7c981de3"

      def install
        bin.install "skpr"
        bin.install "skpr-rsh"

        man1.install "share/man/man1/skpr.1"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
        (bash_completion/"skpr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
        (zsh_completion/"_skpr").write output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skpr/cli/releases/download/v0.29.2/skpr_0.29.2_linux_amd64.tar.gz"
        sha256 "5575672e05d0b9c5e884270e05f7e7107c6b118e227d79294e85e96e4671ba1b"

        def install
          bin.install "skpr"
          bin.install "skpr-rsh"

          man1.install "share/man/man1/skpr.1"

          # Install bash completion
          output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
          (bash_completion/"skpr").write output

          # Install zsh completion
          output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
          (zsh_completion/"_skpr").write output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skpr/cli/releases/download/v0.29.2/skpr_0.29.2_linux_arm64.tar.gz"
        sha256 "36821b7d4b67fd9d113b377aa82df061bd7cd16deae44c8d7a6bb9973b5c7883"

        def install
          bin.install "skpr"
          bin.install "skpr-rsh"

          man1.install "share/man/man1/skpr.1"

          # Install bash completion
          output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-bash")
          (bash_completion/"skpr").write output

          # Install zsh completion
          output = Utils.safe_popen_read("#{bin}/skpr", "--completion-script-zsh")
          (zsh_completion/"_skpr").write output
        end
      end
    end
  end
end
